// Copyright 2026 Firefly Software Foundation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `#[derive(ConfigProperties)]` — Spring `@ConfigurationProperties` /
//! `@EnableConfigurationProperties` parity.
//!
//! Binds a `serde::Deserialize` struct from the container's active config
//! (the `ConditionContext` property map, filtered to a prefix) and registers
//! it as an injectable singleton — so a component can `#[autowired]` it by
//! type, exactly as pyfly's `@config_properties` marks a dataclass injectable.

use darling::FromDeriveInput;
use proc_macro2::TokenStream;
use quote::quote;
use syn::DeriveInput;

use crate::common::facade_from_override;

/// `#[firefly(prefix = "...", crate = "...")]` options on a config-properties
/// struct.
#[derive(FromDeriveInput, Default)]
#[darling(attributes(firefly), supports(struct_named, struct_unit), default)]
struct ConfigPropsOpts {
    #[darling(rename = "crate")]
    krate: Option<String>,
    /// The config-key prefix this struct binds under (e.g. `"app.db"`).
    prefix: Option<String>,
    /// `#[firefly(name = "...")]` — explicit bean name.
    name: Option<String>,
    /// `#[firefly(validate)]` — Spring's `@Validated`: run the struct's
    /// declarative `Validate` constraints after binding, failing context refresh
    /// (the bean's creation) if any constraint is violated. Requires the struct
    /// to also `#[derive(Validate)]`.
    validate: bool,
}

/// Expands `#[derive(ConfigProperties)]`.
pub(crate) fn derive_config_properties(input: DeriveInput) -> syn::Result<TokenStream> {
    let opts = ConfigPropsOpts::from_derive_input(&input).map_err(syn::Error::from)?;
    let facade = facade_from_override(&opts.krate)?;
    let container = facade.container();
    let config = facade.config();
    let validators = facade.validators();
    let ident = &input.ident;
    let generics = &input.generics;
    let (impl_g, ty_g, where_g) = generics.split_for_impl();
    let is_generic = !generics.params.is_empty();

    let prefix = opts.prefix.clone().unwrap_or_default();
    let bean_name = opts.name.clone().unwrap_or_default();
    let type_name_lit = ident.to_string();

    let register_doc = format!(
        "Binds this `#[derive(ConfigProperties)]` struct from config (prefix \
         {prefix:?}) and registers it as an injectable singleton. Generated by \
         the derive; resolve it by type via `#[autowired]`."
    );

    // `#[firefly(validate)]` (Spring's `@Validated`): run the bound struct's
    // declarative `Validate` constraints; a violation fails the bean's creation
    // — i.e. fails context refresh — with the structured per-field errors.
    let validation = if opts.validate {
        quote! {
            .and_then(|__bound| {
                #validators::bean::Validate::validate(&__bound).map_err(|__ve| {
                    #container::ContainerError::NoSuchBean {
                        bean_type: ::core::option::Option::Some(
                            ::core::stringify!(#ident).to_string(),
                        ),
                        bean_name: ::core::option::Option::None,
                        required_by: ::core::option::Option::None,
                        parameter: ::core::option::Option::Some(::std::format!(
                            "#[derive(ConfigProperties)] {} failed @Validated constraints \
                             (prefix {:?}): {:?}",
                            ::core::stringify!(#ident), #prefix, __ve,
                        )),
                        suggestions: ::std::vec::Vec::new(),
                    }
                })?;
                ::core::result::Result::Ok(__bound)
            })
        }
    } else {
        quote! {}
    };

    let register_method = quote! {
        impl #impl_g #ident #ty_g #where_g {
            #[doc = #register_doc]
            pub fn firefly_register(__container: &#container::Container) {
                __container.register_factory::<#ident #ty_g, _>(
                    #container::Scope::Singleton,
                    |__c: &#container::Container| {
                        let __map = __c.config_properties(#prefix);
                        #config::bind::<#ident #ty_g>(&__map).map_err(|__e| {
                            #container::ContainerError::NoSuchBean {
                                bean_type: ::core::option::Option::Some(
                                    ::core::stringify!(#ident).to_string(),
                                ),
                                bean_name: ::core::option::Option::None,
                                required_by: ::core::option::Option::None,
                                parameter: ::core::option::Option::Some(::std::format!(
                                    "failed to bind #[derive(ConfigProperties)] {} from prefix {:?}: {}",
                                    ::core::stringify!(#ident), #prefix, __e,
                                )),
                                suggestions: ::std::vec::Vec::new(),
                            }
                        }) #validation
                    },
                );
                __container.set_stereotype::<#ident #ty_g>("config_properties");
            }
        }
    };

    let inventory_tokens = if is_generic {
        quote! {}
    } else {
        quote! {
            #container::inventory::submit! {
                #container::ComponentRegistration {
                    type_name: #type_name_lit,
                    module_path: ::core::module_path!(),
                    bean_name: #bean_name,
                    stereotype: #container::BeanStereotype::ConfigProperties,
                    scope: #container::Scope::Singleton,
                    primary: false,
                    order: 0,
                    // A config-properties bean is an eagerly warmed singleton.
                    lazy: false,
                    register: <#ident>::firefly_register,
                    conditions: || ::std::vec::Vec::new(),
                }
            }
        }
    };

    Ok(quote! {
        #register_method
        #inventory_tokens
    })
}
