// Copyright 2026 Firefly Software Foundation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The `#[event_listener("topic")]` attribute macro.

use darling::{ast::NestedMeta, FromMeta};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::ItemFn;

use crate::common::facade_from_override;

/// Arguments accepted by `#[event_listener(...)]`. The topic may be given
/// positionally (`#[event_listener("orders.created")]`) or as
/// `#[event_listener(topic = "orders.created", group = "billing")]`.
#[derive(FromMeta, Default)]
#[darling(default)]
struct ListenerArgs {
    #[darling(rename = "crate")]
    krate: Option<String>,
    /// The topic (or glob pattern) to subscribe to.
    topic: Option<String>,
    /// Optional consumer group for competing-consumer delivery.
    group: Option<String>,
    /// Override the generated helper name (default `subscribe_<fn>`).
    register: Option<String>,
}

/// Expands `#[event_listener("topic")]` on an `async fn(Event) -> FireflyResult<()>`.
///
/// A `subscribe_<name>(broker)` async helper is generated that calls
/// `broker.subscribe(topic, handler)` (or `subscribe_group` when a group is
/// given), wrapping the annotated fn as the delivery handler. Returns the
/// broker's `EdaResult<()>` so a failed subscription surfaces to the caller.
pub(crate) fn event_listener_attr(args: TokenStream, item: ItemFn) -> syn::Result<TokenStream> {
    let attr_args = NestedMeta::parse_meta_list(args)?;
    // Allow a bare positional string: `#[event_listener("topic")]`.
    let mut parsed = ListenerArgs::from_list(&attr_args).unwrap_or_default();
    if parsed.topic.is_none() {
        if let Some(NestedMeta::Lit(syn::Lit::Str(s))) = attr_args.first() {
            parsed.topic = Some(s.value());
        }
    }
    let topic = parsed.topic.clone().ok_or_else(|| {
        syn::Error::new_spanned(
            &item.sig,
            "#[event_listener] needs a topic: #[event_listener(\"orders.created\")]",
        )
    })?;

    let facade = facade_from_override(&parsed.krate)?;
    let eda = facade.eda();

    let fn_ident = &item.sig.ident;
    if item.sig.asyncness.is_none() {
        return Err(syn::Error::new_spanned(
            &item.sig,
            "#[event_listener] requires an `async fn`",
        ));
    }
    if item.sig.inputs.len() != 1 {
        return Err(syn::Error::new_spanned(
            &item.sig.inputs,
            "an event listener takes exactly one argument: the `Event`",
        ));
    }

    let register_ident = match &parsed.register {
        Some(name) => format_ident!("{}", name),
        None => format_ident!("subscribe_{}", fn_ident),
    };
    let vis = &item.vis;

    let subscribe_call = match &parsed.group {
        Some(group) if !group.is_empty() => quote! {
            __broker.subscribe_group(#topic, #group, __handler).await
        },
        _ => quote! {
            __broker.subscribe(#topic, __handler).await
        },
    };

    let doc = format!(
        "Subscribes [`{fn}`] to `\"{topic}\"` on the given broker. Generated by \
         `#[event_listener]`; `await` it once at startup.",
        fn = fn_ident
    );

    Ok(quote! {
        #item

        #[doc = #doc]
        #vis async fn #register_ident(
            __broker: &dyn #eda::Broker,
        ) -> #eda::EdaResult<()> {
            let __handler: #eda::Handler = #eda::handler(move |__ev: #eda::Event| async move {
                #fn_ident(__ev).await
            });
            #subscribe_call
        }
    })
}
