// Copyright 2026 Firefly Software Foundation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `#[derive(DomainEvent)]` and `#[derive(AggregateRoot)]`.
//!
//! In `firefly-eventsourcing` the wire shape `DomainEvent` and the bookkeeping
//! `AggregateRoot` are concrete structs (Rust's spelling of Go struct
//! embedding), so these derives do not implement a framework trait — they
//! stamp the idiomatic ergonomics pyfly's `@domain_event` / aggregate base
//! give for free: a stable `event_type()` discriminator (the struct name), a
//! `to_domain_event(...)` conversion onto the framework wire type for a
//! `#[derive(DomainEvent)]` payload, and an `aggregate()` / `aggregate_mut()`
//! accessor pair for a struct that embeds a `firefly_eventsourcing::AggregateRoot`.

use darling::FromDeriveInput;
use proc_macro2::TokenStream;
use quote::quote;
use syn::DeriveInput;

use crate::common::facade_from_override;

/// Options shared by both event-sourcing derives.
#[derive(FromDeriveInput)]
#[darling(attributes(firefly), supports(struct_any))]
struct EsOpts {
    ident: syn::Ident,
    generics: syn::Generics,
    data: darling::ast::Data<darling::util::Ignored, EsField>,
    #[darling(rename = "crate", default)]
    krate: Option<String>,
    /// `#[firefly(event_type = "...")]` — override the discriminator (defaults
    /// to the struct name).
    #[darling(default)]
    event_type: Option<String>,
    /// `#[firefly(aggregate_type = "...")]` — for `#[derive(AggregateRoot)]`,
    /// the type discriminator stamped on raised events (defaults to the struct
    /// name).
    #[darling(default)]
    aggregate_type: Option<String>,
    /// `#[firefly(field = "...")]` — for `#[derive(AggregateRoot)]`, the name
    /// of the embedded `AggregateRoot` field (defaults to `root`).
    #[darling(default)]
    field: Option<String>,
}

/// A field whose only interesting attribute is its name (used to locate the
/// embedded `AggregateRoot`).
#[derive(darling::FromField)]
#[darling(attributes(firefly))]
struct EsField {
    ident: Option<syn::Ident>,
}

/// Expands `#[derive(DomainEvent)]`.
///
/// Requires the type to be `serde::Serialize` (the payload is JSON-encoded into
/// the framework wire event). Generates:
/// - `EVENT_TYPE` associated const + `event_type()` accessor;
/// - `to_domain_event(aggregate_id, aggregate_type, version)` returning a
///   `firefly_eventsourcing::DomainEvent` with the serialized payload.
pub(crate) fn derive_domain_event(input: DeriveInput) -> syn::Result<TokenStream> {
    let opts = EsOpts::from_derive_input(&input).map_err(syn::Error::from)?;
    let facade = facade_from_override(&opts.krate)?;
    let es = facade.eventsourcing();
    let serde_json = facade.serde_json();
    let ident = &opts.ident;
    let (impl_g, ty_g, where_g) = opts.generics.split_for_impl();
    let event_type = opts.event_type.clone().unwrap_or_else(|| ident.to_string());

    if opts.aggregate_type.is_some() || opts.field.is_some() {
        return Err(syn::Error::new_spanned(
            ident,
            "aggregate_type / field are #[derive(AggregateRoot)] options, not #[derive(DomainEvent)]",
        ));
    }

    Ok(quote! {
        impl #impl_g #ident #ty_g #where_g {
            /// The stable event-type discriminator for this domain event —
            /// pyfly's `DomainEvent.event_type`. Generated by
            /// `#[derive(DomainEvent)]`.
            pub const EVENT_TYPE: &'static str = #event_type;

            /// Returns the event-type discriminator (the [`Self::EVENT_TYPE`]
            /// const). Generated by `#[derive(DomainEvent)]`.
            pub fn event_type(&self) -> &'static str {
                Self::EVENT_TYPE
            }

            /// Converts this event into the framework wire
            /// [`firefly_eventsourcing::DomainEvent`], JSON-encoding `self` as
            /// the payload. The `time` field is stamped by the framework's own
            /// `AggregateRoot::raise`, and the payload is encoded through the
            /// facade-re-exported `serde_json` (`::firefly::__rt::serde_json`),
            /// so the generated code references no third-party crate the user
            /// must add beyond the single `firefly` facade. Generated by
            /// `#[derive(DomainEvent)]`.
            ///
            /// # Panics
            /// Panics only if `self` cannot be JSON-serialized, which a
            /// `#[derive(Serialize)]` payload never does.
            pub fn to_domain_event(
                &self,
                aggregate_id: impl ::core::convert::Into<::std::string::String>,
                aggregate_type: impl ::core::convert::Into<::std::string::String>,
                version: i64,
            ) -> #es::DomainEvent {
                let payload = #serde_json::to_vec(self)
                    .expect("firefly-macros: domain event payload must serialize");
                // Build through the framework's own raise() so the `time`
                // stamp and field layout stay owned by firefly-eventsourcing
                // (no direct chrono dependency in the user crate).
                let mut __root = #es::AggregateRoot::new(aggregate_id, aggregate_type);
                __root.version = version.saturating_sub(1);
                __root.raise(Self::EVENT_TYPE, payload);
                __root
                    .take_uncommitted()
                    .pop()
                    .expect("firefly-macros: raise() always buffers one event")
            }
        }
    })
}

/// Expands `#[derive(AggregateRoot)]` on a struct that embeds a
/// `firefly_eventsourcing::AggregateRoot` field (named `root` by default, or
/// `#[firefly(field = "...")]`).
///
/// Generates an `AGGREGATE_TYPE` associated const plus an `aggregate()` /
/// `aggregate_mut()` accessor pair onto the embedded
/// `firefly_eventsourcing::AggregateRoot` — the Rust spelling of pyfly's
/// `AggregateRoot` base class. (Construction stays the caller's responsibility:
/// build the embedded `AggregateRoot` with `AggregateRoot::new(id, type)`.)
pub(crate) fn derive_aggregate_root(input: DeriveInput) -> syn::Result<TokenStream> {
    let opts = EsOpts::from_derive_input(&input).map_err(syn::Error::from)?;
    let facade = facade_from_override(&opts.krate)?;
    let es = facade.eventsourcing();
    let ident = &opts.ident;
    let (impl_g, ty_g, where_g) = opts.generics.split_for_impl();
    let aggregate_type = opts
        .aggregate_type
        .clone()
        .unwrap_or_else(|| ident.to_string());
    let field_name = opts.field.clone().unwrap_or_else(|| "root".to_string());
    let field_ident = syn::Ident::new(&field_name, ident.span());

    // Verify the named field exists and is the right type-ish (best-effort:
    // we only check the field name; the accessor body fails to compile with a
    // clear error if it is not an AggregateRoot).
    let fields = match &opts.data {
        darling::ast::Data::Struct(f) => &f.fields,
        darling::ast::Data::Enum(_) => {
            return Err(syn::Error::new_spanned(
                ident,
                "#[derive(AggregateRoot)] only supports structs",
            ))
        }
    };
    let has_field = fields
        .iter()
        .any(|f| f.ident.as_ref().map(|i| *i == field_ident).unwrap_or(false));
    if !has_field {
        return Err(syn::Error::new_spanned(
            ident,
            format!(
                "#[derive(AggregateRoot)] expects an embedded \
                 `firefly::eventsourcing::AggregateRoot` field named `{field_name}` \
                 (override with #[firefly(field = \"...\")])"
            ),
        ));
    }

    if opts.event_type.is_some() {
        return Err(syn::Error::new_spanned(
            ident,
            "event_type is a #[derive(DomainEvent)] option, not #[derive(AggregateRoot)]",
        ));
    }

    Ok(quote! {
        impl #impl_g #ident #ty_g #where_g {
            /// The aggregate-type discriminator stamped on raised events —
            /// generated by `#[derive(AggregateRoot)]`.
            pub const AGGREGATE_TYPE: &'static str = #aggregate_type;

            /// Borrows the embedded [`firefly_eventsourcing::AggregateRoot`].
            /// Generated by `#[derive(AggregateRoot)]`.
            pub fn aggregate(&self) -> &#es::AggregateRoot {
                &self.#field_ident
            }

            /// Mutably borrows the embedded
            /// [`firefly_eventsourcing::AggregateRoot`] so command methods can
            /// `raise` events. Generated by `#[derive(AggregateRoot)]`.
            pub fn aggregate_mut(&mut self) -> &mut #es::AggregateRoot {
                &mut self.#field_ident
            }
        }
    })
}
