// Copyright 2026 Firefly Software Foundation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `#[derive(SqlxRepository)]` — turns a struct holding a
//! `SqlxReactiveRepository<Entity, Id>` field into a fully-wired `@Repository`
//! **bean**, built from an injected [`Db`](firefly_data_sqlx::Db) datasource.
//!
//! It is the Spring Data experience: declare a repository over an entity and the
//! framework gives you the implementation. The derive
//! 1. registers the struct as a `@Repository` (so it is discovered by
//!    `container.scan()` and classified correctly in `/beans`), constructing it
//!    by resolving the `Db` bean and calling
//!    [`repository_for`](firefly_data_sqlx::repository_for) (table config + row
//!    mapping + `@Version` locking + auditing);
//! 2. implements [`ReactiveCrudRepository`](firefly_data::ReactiveCrudRepository)
//!    by delegating to the inner repository (the "extends ReactiveCrudRepository"
//!    surface); and
//! 3. emits the `repository()` accessor the `#[firefly::repository]` derived
//!    queries build on.
//!
//! The entity supplies its `@Table` / `@Id` / `@Column` mapping via
//! [`SqlxEntity`](firefly_data_sqlx::SqlxEntity) (hand-written, or `#[derive(Entity)]`).

use darling::FromDeriveInput;
use proc_macro2::TokenStream;
use quote::quote;
use syn::{Data, DeriveInput, Fields, GenericArgument, PathArguments, Type};

use crate::common::facade_from_override;

/// The `#[firefly(crate = "...")]` facade override (the only option).
#[derive(FromDeriveInput, Default)]
#[darling(attributes(firefly), supports(struct_named), default)]
struct SqlxRepoOpts {
    #[darling(rename = "crate")]
    krate: Option<String>,
}

/// Expands `#[derive(SqlxRepository)]`.
pub(crate) fn derive_sqlx_repository(input: DeriveInput) -> syn::Result<TokenStream> {
    let self_ty = &input.ident;
    let opts = SqlxRepoOpts::from_derive_input(&input).map_err(syn::Error::from)?;
    let facade = facade_from_override(&opts.krate)?;
    let container = facade.container();
    let rt = facade.rt();

    // Locate the single `SqlxReactiveRepository<Entity, Id>` field.
    let Data::Struct(data) = &input.data else {
        return Err(syn::Error::new_spanned(
            self_ty,
            "#[derive(SqlxRepository)] supports only structs",
        ));
    };
    let Fields::Named(fields) = &data.fields else {
        return Err(syn::Error::new_spanned(
            self_ty,
            "#[derive(SqlxRepository)] needs a named `SqlxReactiveRepository<Entity, Id>` field",
        ));
    };
    let mut found = None;
    for f in &fields.named {
        if let Some((entity, id)) = sqlx_repo_generics(&f.ty) {
            found = Some((f.ident.clone().unwrap(), entity, id));
            break;
        }
    }
    let Some((field, entity_ty, id_ty)) = found else {
        return Err(syn::Error::new_spanned(
            self_ty,
            "#[derive(SqlxRepository)] needs a field of type `SqlxReactiveRepository<Entity, Id>` \
             (the entity must implement `SqlxEntity`)",
        ));
    };

    let type_name_lit = self_ty.to_string();
    let reactive = quote!(#rt::firefly_reactive);
    let data = quote!(#rt::firefly_data);
    let sqlx = quote!(#rt::firefly_data_sqlx);

    Ok(quote! {
        impl #self_ty {
            /// Registers this repository as a `@Repository` bean, built by
            /// resolving the `Db` datasource bean. Generated by
            /// `#[derive(SqlxRepository)]`; `Container::scan()` calls it.
            #[doc(hidden)]
            #[allow(non_snake_case)]
            pub fn firefly_register(__container: &#container::Container) {
                __container.register_factory_with::<#self_ty, _>(
                    #container::Scope::Singleton,
                    "",
                    false,
                    0,
                    |__c: &#container::Container| {
                        let __db = #container::Container::resolve::<#sqlx::Db>(__c)?;
                        ::core::result::Result::Ok(#self_ty {
                            #field: #sqlx::repository_for::<#entity_ty>((*__db).clone()),
                        })
                    },
                );
                __container.set_stereotype::<#self_ty>("repository");
                __container.set_dependencies::<#self_ty>(&["Db"]);
            }

            /// The inner reactive repository — the accessor the
            /// `#[firefly::repository]` derived queries build on.
            #[doc(hidden)]
            fn repository(&self) -> &#sqlx::SqlxReactiveRepository<#entity_ty, #id_ty> {
                &self.#field
            }
        }

        #container::inventory::submit! {
            #container::ComponentRegistration {
                type_name: #type_name_lit,
                module_path: ::core::module_path!(),
                bean_name: "",
                stereotype: #container::BeanStereotype::Repository,
                scope: #container::Scope::Singleton,
                primary: false,
                order: 0,
                lazy: false,
                register: <#self_ty>::firefly_register,
                conditions: || ::std::vec![],
            }
        }

        // "extends ReactiveCrudRepository<Entity, Id>" — delegated to the inner
        // repository so the service programs against the canonical CRUD surface.
        impl #data::ReactiveCrudRepository<#entity_ty, #id_ty> for #self_ty {
            fn find_all(&self) -> #reactive::Flux<#entity_ty> {
                #data::ReactiveCrudRepository::find_all(&self.#field)
            }
            fn find_all_by_id(&self, ids: ::std::vec::Vec<#id_ty>) -> #reactive::Flux<#entity_ty> {
                #data::ReactiveCrudRepository::find_all_by_id(&self.#field, ids)
            }
            fn find_by_id(&self, id: #id_ty) -> #reactive::Mono<#entity_ty> {
                #data::ReactiveCrudRepository::find_by_id(&self.#field, id)
            }
            fn exists_by_id(&self, id: #id_ty) -> #reactive::Mono<bool> {
                #data::ReactiveCrudRepository::exists_by_id(&self.#field, id)
            }
            fn save(&self, entity: #entity_ty) -> #reactive::Mono<#entity_ty> {
                #data::ReactiveCrudRepository::save(&self.#field, entity)
            }
            fn save_all(&self, entities: ::std::vec::Vec<#entity_ty>) -> #reactive::Flux<#entity_ty> {
                #data::ReactiveCrudRepository::save_all(&self.#field, entities)
            }
            fn delete_by_id(&self, id: #id_ty) -> #reactive::Mono<()> {
                #data::ReactiveCrudRepository::delete_by_id(&self.#field, id)
            }
            fn delete_all(&self) -> #reactive::Mono<()> {
                #data::ReactiveCrudRepository::delete_all(&self.#field)
            }
            fn count(&self) -> #reactive::Mono<u64> {
                #data::ReactiveCrudRepository::count(&self.#field)
            }
        }
    })
}

/// Extracts `(Entity, Id)` from a `SqlxReactiveRepository<Entity, Id>` field type.
fn sqlx_repo_generics(ty: &Type) -> Option<(Type, Type)> {
    let Type::Path(tp) = ty else {
        return None;
    };
    let seg = tp.path.segments.last()?;
    if seg.ident != "SqlxReactiveRepository" {
        return None;
    }
    let PathArguments::AngleBracketed(args) = &seg.arguments else {
        return None;
    };
    let mut types = args.args.iter().filter_map(|a| match a {
        GenericArgument::Type(t) => Some(t.clone()),
        _ => None,
    });
    Some((types.next()?, types.next()?))
}
