// Copyright 2026 Firefly Software Foundation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `#[derive(Validate)]` — JSR-380-style declarative bean validation.
//!
//! Reads each field's `#[validate(...)]` constraints and emits an
//! `impl firefly_validators::bean::Validate` whose body runs every
//! constraint, gathering all failures into a single `ValidationErrors`.
//! Unknown constraints become compile errors so a typo never silently
//! drops a check.

use proc_macro2::TokenStream;
use quote::quote;
use syn::punctuated::Punctuated;
use syn::spanned::Spanned;
use syn::{Data, DeriveInput, Expr, Fields, LitStr, Meta, Token};

use crate::common::{facade_from_override, Facade};

/// One parsed `#[validate(...)]` constraint on a field.
enum Constraint {
    /// `email` — RFC 5322 address.
    Email,
    /// `url` — `http`/`https` URL with a host.
    Url,
    /// `not_empty` — non-empty after trimming whitespace.
    NotEmpty,
    /// `length(min = .., max = ..)` — UTF-8 char-count bounds (either bound
    /// optional).
    Length { min: Option<u64>, max: Option<u64> },
    /// `range(min = .., max = ..)` — numeric bounds (either bound optional),
    /// compared with the field value's own type. The `Expr` bounds are boxed so
    /// this variant does not dominate the enum's size (clippy `large_enum_variant`).
    Range {
        min: Option<Box<Expr>>,
        max: Option<Box<Expr>>,
    },
    /// `pattern = "regex"` — the whole value must match the anchored regex.
    Pattern(String),
    /// `custom = "path::to::fn"` — a user predicate
    /// `fn(&FieldTy) -> Result<(), String>`.
    Custom(syn::Path),
}

/// Expands `#[derive(Validate)]` on a named-field struct into an
/// `impl Validate`.
pub(crate) fn derive_validate(input: DeriveInput) -> syn::Result<TokenStream> {
    let ident = &input.ident;
    let (impl_g, ty_g, where_g) = input.generics.split_for_impl();

    // Read an optional container-level `#[validate(crate = "...")]` facade
    // override; every other container-level token is rejected.
    let facade = container_facade(&input)?;
    let validators = facade.validators();

    let data = match &input.data {
        Data::Struct(data) => data,
        Data::Enum(_) | Data::Union(_) => {
            return Err(syn::Error::new_spanned(
                ident,
                "#[derive(Validate)] only supports structs with named fields",
            ));
        }
    };
    let fields = match &data.fields {
        Fields::Named(named) => &named.named,
        Fields::Unnamed(_) | Fields::Unit => {
            return Err(syn::Error::new_spanned(
                ident,
                "#[derive(Validate)] only supports structs with named fields",
            ));
        }
    };

    let mut checks = Vec::new();
    for field in fields {
        let fident = field
            .ident
            .as_ref()
            .expect("named field has an ident by construction");
        let fname = fident.to_string();
        for attr in &field.attrs {
            if !attr.path().is_ident("validate") {
                continue;
            }
            let constraints = parse_field_constraints(attr)?;
            for constraint in constraints {
                checks.push(emit_check(&validators, fident, &fname, &constraint));
            }
        }
    }

    let doc = format!(
        "Runs every `#[validate(...)]` constraint on `{ident}`, collecting all \
         violations into a single `ValidationErrors`. Generated by \
         `#[derive(Validate)]`.",
    );

    Ok(quote! {
        impl #impl_g #validators::bean::Validate for #ident #ty_g #where_g {
            #[doc = #doc]
            fn validate(&self) -> ::core::result::Result<(), #validators::bean::ValidationErrors> {
                let mut __errors = #validators::bean::ValidationErrors::new();
                #(#checks)*
                __errors.into_result()
            }
        }
    })
}

/// Pulls an optional `#[validate(crate = "...")]` off the container; any
/// other container-level `#[validate(...)]` token is a compile error (the
/// constraints belong on fields).
fn container_facade(input: &DeriveInput) -> syn::Result<Facade> {
    let mut krate: Option<String> = None;
    for attr in &input.attrs {
        if !attr.path().is_ident("validate") {
            continue;
        }
        let metas = attr.parse_args_with(Punctuated::<Meta, Token![,]>::parse_terminated)?;
        for meta in metas {
            match &meta {
                Meta::NameValue(nv) if nv.path.is_ident("crate") => {
                    krate = Some(lit_str(&nv.value)?.value());
                }
                other => {
                    return Err(syn::Error::new_spanned(
                        other,
                        "the only container-level `#[validate(...)]` option is \
                         `crate = \"...\"`; put constraints on fields",
                    ));
                }
            }
        }
    }
    facade_from_override(&krate)
}

/// Parses one field's `#[validate(...)]` attribute into its constraints,
/// turning any unknown keyword into a compile error.
fn parse_field_constraints(attr: &syn::Attribute) -> syn::Result<Vec<Constraint>> {
    let metas = attr.parse_args_with(Punctuated::<Meta, Token![,]>::parse_terminated)?;
    let mut out = Vec::new();
    for meta in metas {
        out.push(parse_one(&meta)?);
    }
    if out.is_empty() {
        return Err(syn::Error::new_spanned(
            attr,
            "empty `#[validate()]`; specify at least one constraint \
             (email, url, not_empty, length, range, pattern, custom)",
        ));
    }
    Ok(out)
}

/// Interprets a single `Meta` as a [`Constraint`].
fn parse_one(meta: &Meta) -> syn::Result<Constraint> {
    match meta {
        // Word-style constraints: `email`, `url`, `not_empty`.
        Meta::Path(path) => {
            if path.is_ident("email") {
                Ok(Constraint::Email)
            } else if path.is_ident("url") {
                Ok(Constraint::Url)
            } else if path.is_ident("not_empty") {
                Ok(Constraint::NotEmpty)
            } else {
                Err(unknown(meta, path_name(path)))
            }
        }
        // `pattern = "..."` / `custom = "..."`.
        Meta::NameValue(nv) => {
            if nv.path.is_ident("pattern") {
                let re = lit_str(&nv.value)?.value();
                // Compile-check the pattern at expansion time so an invalid
                // regex is a clear error at the attribute, not a runtime panic
                // in the generated `LazyLock` initializer. Validate the exact
                // anchored form the generated code builds (`^(?:..)$`).
                if let Err(err) = regex::Regex::new(&format!("^(?:{re})$")) {
                    return Err(syn::Error::new_spanned(
                        &nv.value,
                        format!("`#[validate(pattern = ...)]` is not a valid regex: {err}"),
                    ));
                }
                Ok(Constraint::Pattern(re))
            } else if nv.path.is_ident("custom") {
                let lit = lit_str(&nv.value)?;
                let path: syn::Path = lit.parse().map_err(|_| {
                    syn::Error::new_spanned(
                        &nv.value,
                        "`custom` expects a path string, e.g. \
                         custom = \"my_module::check\"",
                    )
                })?;
                Ok(Constraint::Custom(path))
            } else {
                Err(unknown(meta, path_name(&nv.path)))
            }
        }
        // `length(min = .., max = ..)` / `range(min = .., max = ..)`.
        Meta::List(list) => {
            if list.path.is_ident("length") {
                let (min, max) = parse_bounds(list)?;
                let min = min.map(parse_u64).transpose()?;
                let max = max.map(parse_u64).transpose()?;
                if min.is_none() && max.is_none() {
                    return Err(syn::Error::new_spanned(
                        list,
                        "`length` needs at least one of `min` / `max`",
                    ));
                }
                Ok(Constraint::Length { min, max })
            } else if list.path.is_ident("range") {
                let (min, max) = parse_bounds(list)?;
                if min.is_none() && max.is_none() {
                    return Err(syn::Error::new_spanned(
                        list,
                        "`range` needs at least one of `min` / `max`",
                    ));
                }
                Ok(Constraint::Range {
                    min: min.map(Box::new),
                    max: max.map(Box::new),
                })
            } else {
                Err(unknown(meta, path_name(&list.path)))
            }
        }
    }
}

/// Parses the `min = ..` / `max = ..` pair out of a `length(...)` /
/// `range(...)` list, rejecting any other key.
fn parse_bounds(list: &syn::MetaList) -> syn::Result<(Option<Expr>, Option<Expr>)> {
    let nested = list.parse_args_with(Punctuated::<Meta, Token![,]>::parse_terminated)?;
    let mut min = None;
    let mut max = None;
    for meta in nested {
        match &meta {
            Meta::NameValue(nv) if nv.path.is_ident("min") => min = Some(nv.value.clone()),
            Meta::NameValue(nv) if nv.path.is_ident("max") => max = Some(nv.value.clone()),
            other => {
                return Err(syn::Error::new_spanned(
                    other,
                    "expected `min = ..` and/or `max = ..`",
                ));
            }
        }
    }
    Ok((min, max))
}

/// Generates the runtime check for one constraint, pushing a
/// `ValidationError` onto `__errors` on failure. String constraints accept
/// any field whose value `AsRef<str>` (so `String` and `&str` both work);
/// `range` compares with the field's own type.
fn emit_check(
    validators: &TokenStream,
    fident: &syn::Ident,
    fname: &str,
    constraint: &Constraint,
) -> TokenStream {
    let push = |code: &str, message: TokenStream| {
        quote! {
            __errors.push(#validators::bean::ValidationError::new(#fname, #code, #message));
        }
    };
    match constraint {
        Constraint::Email => {
            let body = push(
                "email",
                quote!(::core::format!("`{}` is not a valid email address", #fname)),
            );
            quote! {
                if #validators::validate_email(::core::convert::AsRef::<str>::as_ref(&self.#fident)).is_err() {
                    #body
                }
            }
        }
        Constraint::Url => {
            let body = push(
                "url",
                quote!(::core::format!("`{}` is not a valid URL", #fname)),
            );
            // No standalone URL predicate in the validators crate; apply a
            // minimal scheme+host check inline (http/https with a non-empty
            // authority and no whitespace), matching the other ports'
            // lightweight URL format rule.
            quote! {
                {
                    let __v: &str = ::core::convert::AsRef::<str>::as_ref(&self.#fident);
                    let __ok = (__v.starts_with("http://") || __v.starts_with("https://"))
                        && !__v.chars().any(char::is_whitespace)
                        && __v
                            .split_once("://")
                            .map(|(_, rest)| {
                                let host = rest.split(['/', '?', '#']).next().unwrap_or("");
                                !host.is_empty()
                            })
                            .unwrap_or(false);
                    if !__ok {
                        #body
                    }
                }
            }
        }
        Constraint::NotEmpty => {
            let body = push(
                "not_empty",
                quote!(::core::format!("`{}` must not be empty", #fname)),
            );
            quote! {
                if ::core::convert::AsRef::<str>::as_ref(&self.#fident).trim().is_empty() {
                    #body
                }
            }
        }
        Constraint::Length { min, max } => {
            let mut clauses = Vec::new();
            if let Some(min) = min {
                let body = push(
                    "length",
                    quote!(::core::format!("`{}` must be at least {} characters", #fname, #min)),
                );
                clauses.push(quote! {
                    if __len < #min { #body }
                });
            }
            if let Some(max) = max {
                let body = push(
                    "length",
                    quote!(::core::format!("`{}` must be at most {} characters", #fname, #max)),
                );
                clauses.push(quote! {
                    if __len > #max { #body }
                });
            }
            quote! {
                {
                    let __len: u64 =
                        ::core::convert::AsRef::<str>::as_ref(&self.#fident).chars().count() as u64;
                    #(#clauses)*
                }
            }
        }
        Constraint::Range { min, max } => {
            let mut clauses = Vec::new();
            if let Some(min) = min {
                let body = push(
                    "range",
                    quote!(::core::format!("`{}` must be at least {}", #fname, #min)),
                );
                clauses.push(quote! {
                    if self.#fident < #min { #body }
                });
            }
            if let Some(max) = max {
                let body = push(
                    "range",
                    quote!(::core::format!("`{}` must be at most {}", #fname, #max)),
                );
                clauses.push(quote! {
                    if self.#fident > #max { #body }
                });
            }
            quote! { #(#clauses)* }
        }
        Constraint::Pattern(re) => {
            let body = push(
                "pattern",
                quote!(::core::format!("`{}` does not match the required pattern", #fname)),
            );
            // Compile the regex once per check site with a thread-safe
            // `LazyLock`, resolved through the validators crate's re-exported
            // `regex` so the user crate needs no `regex` dependency. The
            // pattern is anchored so the whole value must match (JSR-380
            // `@Pattern` semantics).
            quote! {
                {
                    static __RE: #validators::bean::__rt::LazyLock<#validators::bean::__rt::Regex> =
                        #validators::bean::__rt::LazyLock::new(|| {
                            #validators::bean::__rt::Regex::new(::core::concat!("^(?:", #re, ")$"))
                                .expect("`#[validate(pattern = ...)]` regex is invalid")
                        });
                    if !__RE.is_match(::core::convert::AsRef::<str>::as_ref(&self.#fident)) {
                        #body
                    }
                }
            }
        }
        Constraint::Custom(path) => {
            // The user predicate is `fn(&FieldTy) -> Result<(), String>`; its
            // returned message becomes the violation message.
            quote! {
                if let ::core::result::Result::Err(__msg) = #path(&self.#fident) {
                    __errors.push(
                        #validators::bean::ValidationError::new(#fname, "custom", __msg)
                    );
                }
            }
        }
    }
}

/// Builds the "unknown constraint" diagnostic, listing the supported set.
fn unknown(meta: &Meta, name: String) -> syn::Error {
    syn::Error::new(
        meta.span(),
        format!(
            "unknown validation constraint `{name}`; supported: email, url, \
             not_empty, length(min, max), range(min, max), pattern = \"..\", \
             custom = \"path::to::fn\""
        ),
    )
}

/// Renders a path as a dotted name for diagnostics.
fn path_name(path: &syn::Path) -> String {
    path.segments
        .iter()
        .map(|s| s.ident.to_string())
        .collect::<Vec<_>>()
        .join("::")
}

/// Extracts a string literal out of an expression, erroring otherwise.
fn lit_str(expr: &Expr) -> syn::Result<LitStr> {
    if let Expr::Lit(lit) = expr {
        if let syn::Lit::Str(s) = &lit.lit {
            return Ok(s.clone());
        }
    }
    Err(syn::Error::new_spanned(expr, "expected a string literal"))
}

/// Parses an expression that must be an integer literal into a `u64`
/// (used for `length` bounds, which are character counts).
fn parse_u64(expr: Expr) -> syn::Result<u64> {
    if let Expr::Lit(lit) = &expr {
        if let syn::Lit::Int(int) = &lit.lit {
            return int.base10_parse::<u64>();
        }
    }
    Err(syn::Error::new_spanned(
        expr,
        "`length` bounds must be unsigned integer literals",
    ))
}
