// Copyright 2026 Firefly Software Foundation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! End-to-end test for the `#[repository]` declarative derived-query macro:
//! typed `find_by_…` / `count_by_…` / `exists_by_…` methods, generated over a
//! real SQLite repository.

use std::str::FromStr;
use std::sync::Arc;

use firefly::container::Container;
use firefly::data::{DataError, Order, Pageable, ReactiveCrudRepository, RequestSort, TableConfig};
use firefly::data_sqlx::{AnyRow, ColumnValue, Db, SqlxEntity, SqlxReactiveRepository};
use firefly::kernel::FireflyError;

/// Opens a **shared-cache** in-memory SQLite pool under a unique `name`. A
/// shared-cache DB lets a multi-connection pool see one database, so a streamed
/// query that briefly holds a connection can never wedge the next query — the
/// deadlock a single-connection `sqlite::memory:` pool hits under parallel load.
async fn shared_memory_pool(name: &str) -> sqlx::SqlitePool {
    let url = format!("sqlite:file:{name}?mode=memory&cache=shared");
    let opts = sqlx::sqlite::SqliteConnectOptions::from_str(&url)
        .expect("sqlite connect options")
        .busy_timeout(std::time::Duration::from_secs(5));
    sqlx::sqlite::SqlitePoolOptions::new()
        .min_connections(1)
        .max_connections(5)
        .connect_with(opts)
        .await
        .expect("open shared-cache in-memory sqlite")
}

#[derive(Debug, Clone, PartialEq)]
struct Account {
    id: i64,
    owner: String,
    status: String,
}

fn map_account(row: &AnyRow<'_>) -> Result<Account, FireflyError> {
    Ok(Account {
        id: row.get_i64("id")?,
        owner: row.get_str("owner")?,
        status: row.get_str("status")?,
    })
}

fn write_account(a: &Account) -> Vec<ColumnValue> {
    vec![
        ColumnValue::new("id", a.id),
        ColumnValue::new("owner", a.owner.clone()),
        ColumnValue::new("status", a.status.clone()),
    ]
}

struct AccountRepo {
    repo: SqlxReactiveRepository<Account, i64>,
}

impl AccountRepo {
    fn repository(&self) -> &SqlxReactiveRepository<Account, i64> {
        &self.repo
    }
}

// The declarative derived-query surface — bodies generated by the macro.
#[firefly::repository]
impl AccountRepo {
    async fn find_by_status(&self, status: &str) -> Result<Vec<Account>, DataError> {
        unimplemented!()
    }
    async fn count_by_status(&self, status: &str) -> Result<i64, DataError> {
        unimplemented!()
    }
    async fn exists_by_owner(&self, owner: &str) -> Result<bool, DataError> {
        unimplemented!()
    }

    // Paged derived query — a trailing `Pageable` appends ORDER BY/LIMIT/OFFSET
    // to the name-derived predicate (Spring's `findByOwner(owner, Pageable)`).
    async fn find_by_owner(&self, owner: &str, page: Pageable) -> Result<Vec<Account>, DataError> {
        unimplemented!()
    }

    // `@query` native SQL — `:status` binds to the `status` argument by name.
    #[query("SELECT id, owner, status FROM accounts WHERE status = :status ORDER BY id DESC")]
    async fn ranked_by_status(&self, status: &str) -> Result<Vec<Account>, DataError> {
        unimplemented!()
    }

    // `@query` count.
    #[query("SELECT COUNT(*) FROM accounts WHERE owner = :owner")]
    async fn owned(&self, owner: &str) -> Result<i64, DataError> {
        unimplemented!()
    }

    // `@query` modifying — returns the affected row count.
    #[query("UPDATE accounts SET status = :to WHERE status = :from")]
    async fn migrate_status(&self, from: &str, to: &str) -> Result<u64, DataError> {
        unimplemented!()
    }
}

#[tokio::test]
async fn declarative_derived_queries_execute() {
    let pool = shared_memory_pool("firefly_repo_derived").await;
    sqlx::query(
        "CREATE TABLE accounts (id INTEGER PRIMARY KEY, owner TEXT NOT NULL, status TEXT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("create table");

    let cfg = TableConfig::new("accounts", "id", ["id", "owner", "status"]);
    let repo = SqlxReactiveRepository::new(Db::Sqlite(pool), cfg, map_account, write_account);

    for (id, owner, status) in [
        (1, "ada", "active"),
        (2, "bob", "closed"),
        (3, "cy", "active"),
    ] {
        repo.save(Account {
            id,
            owner: owner.into(),
            status: status.into(),
        })
        .into_future()
        .await
        .expect("seed save");
    }

    let api = AccountRepo { repo };

    // find_by_status → Vec<Account>
    let active = api.find_by_status("active").await.expect("find");
    assert_eq!(active.len(), 2, "two active accounts");

    // count_by_status → i64
    assert_eq!(api.count_by_status("active").await.expect("count"), 2);
    assert_eq!(api.count_by_status("closed").await.expect("count"), 1);

    // exists_by_owner → bool
    assert!(api.exists_by_owner("ada").await.expect("exists"));
    assert!(!api.exists_by_owner("nobody").await.expect("exists"));
}

#[tokio::test]
async fn paged_and_custom_queries_execute() {
    let pool = shared_memory_pool("firefly_repo_paged").await;
    sqlx::query(
        "CREATE TABLE accounts (id INTEGER PRIMARY KEY, owner TEXT NOT NULL, status TEXT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("create table");

    let cfg = TableConfig::new("accounts", "id", ["id", "owner", "status"]);
    let repo = SqlxReactiveRepository::new(Db::Sqlite(pool), cfg, map_account, write_account);

    // `ada` owns two rows so paging is observable.
    for (id, owner, status) in [
        (1, "ada", "active"),
        (2, "ada", "closed"),
        (3, "bob", "active"),
        (4, "cy", "active"),
    ] {
        repo.save(Account {
            id,
            owner: owner.into(),
            status: status.into(),
        })
        .into_future()
        .await
        .expect("seed save");
    }

    let api = AccountRepo { repo };

    // Paged derived query: ada's rows, one per page, newest id first.
    // Pages are 1-based (matching Spring/pyfly).
    let page1 = api
        .find_by_owner(
            "ada",
            Pageable::of(1, 1, RequestSort::of([Order::desc("id")])).unwrap(),
        )
        .await
        .expect("paged find");
    assert_eq!(page1.len(), 1, "page size 1");
    assert_eq!(page1[0].id, 2, "newest id first");
    let page2 = api
        .find_by_owner(
            "ada",
            Pageable::of(2, 1, RequestSort::of([Order::desc("id")])).unwrap(),
        )
        .await
        .expect("paged find");
    assert_eq!(page2[0].id, 1, "second page is the older row");

    // @query (native list): active accounts, id descending.
    let ranked = api.ranked_by_status("active").await.expect("ranked");
    assert_eq!(
        ranked.iter().map(|a| a.id).collect::<Vec<_>>(),
        vec![4, 3, 1],
        "three active accounts, id DESC"
    );

    // @query (count).
    assert_eq!(api.owned("ada").await.expect("owned count"), 2);

    // @query (modifying): promote the single closed account to active.
    let migrated = api
        .migrate_status("closed", "active")
        .await
        .expect("migrate");
    assert_eq!(migrated, 1, "one closed account promoted");
    assert_eq!(
        api.ranked_by_status("active").await.expect("ranked").len(),
        4,
        "all four are now active"
    );
}

// ── #[derive(SqlxRepository)] — Spring-Data-style @Repository from a Db bean ──

#[derive(Debug, Clone, PartialEq)]
struct Doc {
    id: i64,
    title: String,
    status: String,
}

impl SqlxEntity for Doc {
    type Id = i64;
    fn table() -> &'static str {
        "docs"
    }
    fn id_column() -> &'static str {
        "id"
    }
    fn columns() -> &'static [&'static str] {
        &["id", "title", "status"]
    }
    fn read_row(row: &AnyRow<'_>) -> Result<Self, FireflyError> {
        Ok(Doc {
            id: row.get_i64("id")?,
            title: row.get_str("title")?,
            status: row.get_str("status")?,
        })
    }
    fn write_row(&self) -> Vec<ColumnValue> {
        vec![
            ColumnValue::new("id", self.id),
            ColumnValue::new("title", self.title.clone()),
            ColumnValue::new("status", self.status.clone()),
        ]
    }
}

/// A repository declared the Spring Data way: one annotation over the entity.
#[derive(firefly::SqlxRepository)]
struct DocRepo {
    repo: SqlxReactiveRepository<Doc, i64>,
}

#[firefly::repository]
impl DocRepo {
    async fn find_by_status(&self, status: &str) -> Result<Vec<Doc>, DataError> {
        unimplemented!()
    }
}

#[tokio::test]
async fn sqlx_repository_derive_builds_from_the_db_bean() {
    let pool = shared_memory_pool("firefly_sqlx_repo_derive").await;
    sqlx::query(
        "CREATE TABLE docs (id INTEGER PRIMARY KEY, title TEXT NOT NULL, status TEXT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("create table");

    // The container holds only the `Db` datasource bean; the repository is
    // built from it by the derive (no hand-written #[bean] factory).
    let c = Arc::new(Container::new());
    c.register_instance(Db::Sqlite(pool));
    DocRepo::firefly_register(&c); // what Container::scan() calls.

    let repo = c
        .resolve::<DocRepo>()
        .expect("DocRepo resolves from the Db bean");

    // CRUD via the derived `ReactiveCrudRepository` delegation.
    for (id, title, status) in [(1, "a", "open"), (2, "b", "open"), (3, "c", "closed")] {
        repo.save(Doc {
            id,
            title: title.into(),
            status: status.into(),
        })
        .await
        .expect("save");
    }
    let got = repo.find_by_id(1).await.expect("find").expect("present");
    assert_eq!(got.title, "a");
    assert_eq!(repo.count().await.expect("count").unwrap_or(0), 3);

    // The `#[firefly::repository]` derived query, via the generated accessor.
    let open = repo.find_by_status("open").await.expect("by status");
    assert_eq!(open.len(), 2);

    // Classified as @Repository in /beans (not a generic @Bean).
    let label = c
        .beans()
        .iter()
        .find(|b| b.type_name.ends_with("DocRepo"))
        .and_then(|b| b.stereotype.clone());
    assert_eq!(label.as_deref(), Some("repository"));
}

// ── #[derive(Entity)] — auto-generated SqlxEntity mapping over diverse types ──

#[derive(Debug, Clone, PartialEq, firefly::Entity)]
#[firefly(table = "gadgets")]
struct Gadget {
    #[firefly(id)]
    id: i64,
    name: String,
    #[firefly(column = "qty")]
    quantity: i32,
    active: bool,
    weight: f64,
    #[firefly(version)]
    version: i64,
}

#[derive(firefly::SqlxRepository)]
struct GadgetRepo {
    repo: SqlxReactiveRepository<Gadget, i64>,
}

#[tokio::test]
async fn entity_derive_maps_scalar_types_and_renames() {
    let pool = shared_memory_pool("firefly_entity_derive").await;
    sqlx::query(
        "CREATE TABLE gadgets (id INTEGER PRIMARY KEY, name TEXT NOT NULL, qty INTEGER NOT NULL, \
         active INTEGER NOT NULL, weight REAL NOT NULL, version INTEGER NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("create table");

    // SqlxEntity metadata is generated from the fields + attributes.
    assert_eq!(<Gadget as SqlxEntity>::table(), "gadgets");
    assert_eq!(<Gadget as SqlxEntity>::id_column(), "id");
    assert_eq!(<Gadget as SqlxEntity>::version_column(), Some("version"));
    assert_eq!(
        <Gadget as SqlxEntity>::columns(),
        &["id", "name", "qty", "active", "weight", "version"]
    );

    let c = Arc::new(Container::new());
    c.register_instance(Db::Sqlite(pool));
    GadgetRepo::firefly_register(&c);
    let repo = c.resolve::<GadgetRepo>().expect("gadget repo");

    let g = Gadget {
        id: 1,
        name: "widget".into(),
        quantity: 7,
        active: true,
        weight: 2.5,
        version: 1,
    };
    repo.save(g.clone()).await.expect("save");
    let loaded = repo.find_by_id(1).await.expect("find").expect("present");
    assert_eq!(loaded.name, "widget");
    assert_eq!(loaded.quantity, 7); // renamed column `qty` round-trips
    assert!(loaded.active);
    assert_eq!(loaded.weight, 2.5);
}
