// Copyright 2026 Firefly Software Foundation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! End-to-end test for the `#[repository]` declarative derived-query macro:
//! typed `find_by_…` / `count_by_…` / `exists_by_…` methods, generated over a
//! real SQLite repository.

use std::str::FromStr;

use firefly::data::{DataError, Order, Pageable, ReactiveCrudRepository, RequestSort, TableConfig};
use firefly::data_sqlx::{AnyRow, ColumnValue, Db, SqlxReactiveRepository};
use firefly::kernel::FireflyError;

/// Opens a **shared-cache** in-memory SQLite pool under a unique `name`. A
/// shared-cache DB lets a multi-connection pool see one database, so a streamed
/// query that briefly holds a connection can never wedge the next query — the
/// deadlock a single-connection `sqlite::memory:` pool hits under parallel load.
async fn shared_memory_pool(name: &str) -> sqlx::SqlitePool {
    let url = format!("sqlite:file:{name}?mode=memory&cache=shared");
    let opts = sqlx::sqlite::SqliteConnectOptions::from_str(&url)
        .expect("sqlite connect options")
        .busy_timeout(std::time::Duration::from_secs(5));
    sqlx::sqlite::SqlitePoolOptions::new()
        .min_connections(1)
        .max_connections(5)
        .connect_with(opts)
        .await
        .expect("open shared-cache in-memory sqlite")
}

#[derive(Debug, Clone, PartialEq)]
struct Account {
    id: i64,
    owner: String,
    status: String,
}

fn map_account(row: &AnyRow<'_>) -> Result<Account, FireflyError> {
    Ok(Account {
        id: row.get_i64("id")?,
        owner: row.get_str("owner")?,
        status: row.get_str("status")?,
    })
}

fn write_account(a: &Account) -> Vec<ColumnValue> {
    vec![
        ColumnValue::new("id", a.id),
        ColumnValue::new("owner", a.owner.clone()),
        ColumnValue::new("status", a.status.clone()),
    ]
}

struct AccountRepo {
    repo: SqlxReactiveRepository<Account, i64>,
}

impl AccountRepo {
    fn repository(&self) -> &SqlxReactiveRepository<Account, i64> {
        &self.repo
    }
}

// The declarative derived-query surface — bodies generated by the macro.
#[firefly::repository]
impl AccountRepo {
    async fn find_by_status(&self, status: &str) -> Result<Vec<Account>, DataError> {
        unimplemented!()
    }
    async fn count_by_status(&self, status: &str) -> Result<i64, DataError> {
        unimplemented!()
    }
    async fn exists_by_owner(&self, owner: &str) -> Result<bool, DataError> {
        unimplemented!()
    }

    // Paged derived query — a trailing `Pageable` appends ORDER BY/LIMIT/OFFSET
    // to the name-derived predicate (Spring's `findByOwner(owner, Pageable)`).
    async fn find_by_owner(&self, owner: &str, page: Pageable) -> Result<Vec<Account>, DataError> {
        unimplemented!()
    }

    // `@query` native SQL — `:status` binds to the `status` argument by name.
    #[query("SELECT id, owner, status FROM accounts WHERE status = :status ORDER BY id DESC")]
    async fn ranked_by_status(&self, status: &str) -> Result<Vec<Account>, DataError> {
        unimplemented!()
    }

    // `@query` count.
    #[query("SELECT COUNT(*) FROM accounts WHERE owner = :owner")]
    async fn owned(&self, owner: &str) -> Result<i64, DataError> {
        unimplemented!()
    }

    // `@query` modifying — returns the affected row count.
    #[query("UPDATE accounts SET status = :to WHERE status = :from")]
    async fn migrate_status(&self, from: &str, to: &str) -> Result<u64, DataError> {
        unimplemented!()
    }
}

#[tokio::test]
async fn declarative_derived_queries_execute() {
    let pool = shared_memory_pool("firefly_repo_derived").await;
    sqlx::query(
        "CREATE TABLE accounts (id INTEGER PRIMARY KEY, owner TEXT NOT NULL, status TEXT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("create table");

    let cfg = TableConfig::new("accounts", "id", ["id", "owner", "status"]);
    let repo = SqlxReactiveRepository::new(Db::Sqlite(pool), cfg, map_account, write_account);

    for (id, owner, status) in [
        (1, "ada", "active"),
        (2, "bob", "closed"),
        (3, "cy", "active"),
    ] {
        repo.save(Account {
            id,
            owner: owner.into(),
            status: status.into(),
        })
        .into_future()
        .await
        .expect("seed save");
    }

    let api = AccountRepo { repo };

    // find_by_status → Vec<Account>
    let active = api.find_by_status("active").await.expect("find");
    assert_eq!(active.len(), 2, "two active accounts");

    // count_by_status → i64
    assert_eq!(api.count_by_status("active").await.expect("count"), 2);
    assert_eq!(api.count_by_status("closed").await.expect("count"), 1);

    // exists_by_owner → bool
    assert!(api.exists_by_owner("ada").await.expect("exists"));
    assert!(!api.exists_by_owner("nobody").await.expect("exists"));
}

#[tokio::test]
async fn paged_and_custom_queries_execute() {
    let pool = shared_memory_pool("firefly_repo_paged").await;
    sqlx::query(
        "CREATE TABLE accounts (id INTEGER PRIMARY KEY, owner TEXT NOT NULL, status TEXT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("create table");

    let cfg = TableConfig::new("accounts", "id", ["id", "owner", "status"]);
    let repo = SqlxReactiveRepository::new(Db::Sqlite(pool), cfg, map_account, write_account);

    // `ada` owns two rows so paging is observable.
    for (id, owner, status) in [
        (1, "ada", "active"),
        (2, "ada", "closed"),
        (3, "bob", "active"),
        (4, "cy", "active"),
    ] {
        repo.save(Account {
            id,
            owner: owner.into(),
            status: status.into(),
        })
        .into_future()
        .await
        .expect("seed save");
    }

    let api = AccountRepo { repo };

    // Paged derived query: ada's rows, one per page, newest id first.
    // Pages are 1-based (matching Spring/pyfly).
    let page1 = api
        .find_by_owner(
            "ada",
            Pageable::of(1, 1, RequestSort::of([Order::desc("id")])).unwrap(),
        )
        .await
        .expect("paged find");
    assert_eq!(page1.len(), 1, "page size 1");
    assert_eq!(page1[0].id, 2, "newest id first");
    let page2 = api
        .find_by_owner(
            "ada",
            Pageable::of(2, 1, RequestSort::of([Order::desc("id")])).unwrap(),
        )
        .await
        .expect("paged find");
    assert_eq!(page2[0].id, 1, "second page is the older row");

    // @query (native list): active accounts, id descending.
    let ranked = api.ranked_by_status("active").await.expect("ranked");
    assert_eq!(
        ranked.iter().map(|a| a.id).collect::<Vec<_>>(),
        vec![4, 3, 1],
        "three active accounts, id DESC"
    );

    // @query (count).
    assert_eq!(api.owned("ada").await.expect("owned count"), 2);

    // @query (modifying): promote the single closed account to active.
    let migrated = api
        .migrate_status("closed", "active")
        .await
        .expect("migrate");
    assert_eq!(migrated, 1, "one closed account promoted");
    assert_eq!(
        api.ranked_by_status("active").await.expect("ranked").len(),
        4,
        "all four are now active"
    );
}
