# syntax=docker/dockerfile:1
FROM rust:1.88-slim AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/{{ package_name }} /usr/local/bin/{{ package_name }}
{% if has_data %}COPY --from=builder /app/migrations /app/migrations
{% endif %}COPY --from=builder /app/firefly.yaml /app/firefly.yaml
EXPOSE 8080
CMD ["{{ package_name }}"]
