// Copyright 2026 Firefly Software Foundation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The [`WalletRepository`] — a Spring Data-style `@Repository`.

use firefly::data::{DataError, Pageable};
use firefly::data_sqlx::SqlxReactiveRepository;
use uuid::Uuid;

use crate::entities::wallet::v1::Wallet;

/// The wallet persistence boundary — Spring Data's `WalletRepository`.
///
/// One annotation does it all: `#[derive(SqlxRepository)]` registers this as a
/// **`@Repository` bean built from the injected `Db` datasource** (table config,
/// `@Version` optimistic locking, and `@CreatedDate`/`@LastModifiedDate`
/// auditing are wired from the [`Wallet`] entity's
/// [`SqlxEntity`](firefly::data_sqlx::SqlxEntity) mapping), and implements
/// [`ReactiveCrudRepository`](firefly::data::ReactiveCrudRepository) by
/// delegation — exactly like a Spring Data
/// `interface WalletRepository extends ReactiveCrudRepository<Wallet, UUID>`.
/// The `#[firefly::repository]` block below adds the derived queries on top.
///
/// No `#[bean]` factory and no hand-written CRUD: the only state is the inner
/// `SqlxReactiveRepository`, which the derive builds from the autowired `Db`.
#[derive(firefly::SqlxRepository)]
pub struct WalletRepository {
    repo: SqlxReactiveRepository<Wallet, Uuid>,
}

// The declarative derived-query surface — method bodies generated by
// `#[firefly::repository]` from each method name (Spring Data style), reaching
// the inner repository through the accessor `#[derive(SqlxRepository)]` emits.
#[firefly::repository]
impl WalletRepository {
    /// `SELECT … WHERE owner = ?` — every wallet of one owner.
    pub async fn find_by_owner(&self, owner: &str) -> Result<Vec<Wallet>, DataError> {
        unimplemented!()
    }

    /// `SELECT COUNT(*) WHERE status = ?`.
    pub async fn count_by_status(&self, status: &str) -> Result<i64, DataError> {
        unimplemented!()
    }

    /// Paged `SELECT … WHERE status = ?` (ORDER BY/LIMIT/OFFSET from the
    /// trailing [`Pageable`]).
    pub async fn find_by_status(
        &self,
        status: &str,
        page: Pageable,
    ) -> Result<Vec<Wallet>, DataError> {
        unimplemented!()
    }
}

#[cfg(test)]
mod tests {
    use chrono::Utc;
    use firefly::data::{DataError, Pageable, ReactiveCrudRepository, RequestSort};
    use firefly::data_sqlx::repository_for;
    use lumen_ledger_interfaces::WalletStatus;
    use uuid::Uuid;

    use super::WalletRepository;
    use crate::config::connect_and_migrate_url;
    use crate::entities::wallet::v1::Wallet;

    fn sample(owner: &str, status: WalletStatus) -> Wallet {
        Wallet {
            id: Uuid::new_v4(),
            account_number: format!("WAL-{owner}-{}", Uuid::new_v4()),
            owner: owner.into(),
            balance: 100,
            currency: "EUR".into(),
            status,
            version: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    /// Builds the repository directly for a unit test (the production wiring
    /// resolves the `Db` bean; here we build over an isolated in-memory DB). The
    /// derive's bean factory uses this same `repository_for` path.
    async fn repo(cache: &str) -> WalletRepository {
        let url = format!("sqlite:file:{cache}?mode=memory&cache=shared");
        WalletRepository {
            repo: repository_for::<Wallet>(connect_and_migrate_url(&url).await),
        }
    }

    #[tokio::test]
    async fn repository_saves_and_runs_derived_queries() {
        let repo = repo("lumen_models_derived").await;

        let ada = sample("ada", WalletStatus::Active);
        let id = ada.id;
        repo.save(ada).await.expect("save ada");
        repo.save(sample("ada", WalletStatus::Frozen))
            .await
            .expect("save 2");
        repo.save(sample("bob", WalletStatus::Active))
            .await
            .expect("save bob");

        assert_eq!(repo.count().await.expect("count").unwrap_or(0), 3);

        // find_by_id round-trips the typed status enum.
        let found = repo.find_by_id(id).await.expect("find").expect("present");
        assert_eq!(found.owner, "ada");
        assert_eq!(found.status, WalletStatus::Active);

        assert_eq!(repo.find_by_owner("ada").await.expect("by owner").len(), 2);
        assert_eq!(repo.count_by_status("active").await.expect("count"), 2);
        assert_eq!(repo.count_by_status("frozen").await.expect("count"), 1);

        // Paged derived query (the only Pageable machinery in the sample).
        let page = repo
            .find_by_status(
                "active",
                Pageable::of(1, 1, RequestSort::of([])).expect("pageable"),
            )
            .await
            .expect("paged");
        assert_eq!(page.len(), 1, "page size 1 of the active wallets");

        assert!(repo
            .find_by_id(Uuid::new_v4())
            .await
            .expect("absent")
            .is_none());
    }

    #[tokio::test]
    async fn optimistic_locking_rejects_a_stale_write() {
        let repo = repo("lumen_models_optlock").await;
        let wallet = sample("ada", WalletStatus::Active);
        let id = wallet.id;
        repo.save(wallet).await.expect("insert");

        // Two readers load the same version.
        let a = repo.find_by_id(id).await.expect("load a").expect("present");
        let b = repo.find_by_id(id).await.expect("load b").expect("present");

        // First writer wins (the store bumps version).
        let mut a = a;
        a.balance += 10;
        repo.save(a).await.expect("first write wins");

        // Second writer holds the stale version → @Version conflict.
        let mut b = b;
        b.balance += 20;
        let err = repo.save(b).await.expect_err("stale write must conflict");
        assert!(
            firefly::data_sqlx::is_optimistic_lock(&err),
            "stale @Version write is an optimistic-lock conflict, got: {err}"
        );
    }

    // Belt-and-suspenders: the audit columns round-trip through the entity.
    #[tokio::test]
    async fn auditor_stamps_round_trip() -> Result<(), DataError> {
        let repo = repo("lumen_models_audit").await;
        let w = sample("ada", WalletStatus::Active);
        let id = w.id;
        repo.save(w)
            .await
            .map_err(|e| DataError::Backend(e.to_string()))?;
        let loaded = repo
            .find_by_id(id)
            .await
            .map_err(|e| DataError::Backend(e.to_string()))?;
        assert!(loaded.is_some(), "audit-stamped row reads back");
        Ok(())
    }
}
